### ISSUE TITLE
[feature] Rewrite doi.org links to oadoi.org

### ISSUE THREAD

**Issue by jibe-b** [Impactstory/unpaywall#16]
One may click on a DOI link which uses doi.org to resolve it.

In order to accelerate the pace at which one lands on a OA version of a publication, it could be useful to rewrite the redirection to doi.org to oadoi.org, so that there is no extra need to click on the unpaywall icon.

This may be an _opt-in_ feature. It may also be associated to a slight popup indicating oadoi.org was used to resolve this DOI.

**Comment by jibe-b** [comment]
@jasonpriem Is this the good place where to suggest features or should I write somewhere else?

**Comment by hpiwowar** [comment]
Great news! If I understand you correctly, this already exists.

instead of
http://api.oadoi.org/10.1038/nature21360

visit this in a browser (no "api." in front):
http://oadoi.org/10.1038/nature21360

it automatically redirects to the oadoi url whenever it is a paywall
article and we found a non-paywall copy :)

Heather




--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by jibe-b** [comment]
Thank you for your answer, @hpiwowar 

Here is an example to let you understand better what I suggest:

on https://www.ncbi.nlm.nih.gov/pubmed/28733324 the DOI is present and a link is provided, which uses doi.org to resolve the DOI (and land on a paywall).

The Unpaywall extension could rewrite the html at load time (hence the href will point to oadoi.org).

This would be done by parsing the html and whenever the regex like http\*://doi.org/\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?!["&\'<>])\S)+)\b is matched.

**Comment by jibe-b** [comment]
One possible hack is

```{javascript}
all = document.getElementsByTagName('div');
for (item of all){
  if (item.innerHTML.match(/\/\/doi.org/)) {
    item.innerHTML = item.innerHTML.replace(/\/\/doi.org/, '//oadoi.org')
  }
}
```
Note: this hack is not optimal as the same string is matched several times

**Comment by jasonpriem** [comment]
Sorry for the delay! Thanks for clarifying. This is a good idea, but we think it is out of scope for Unpaywall right now. That's mostly because Unpaywall essentially already does this...when you click on a DOI link, after your browser follows it you'll see a green Unpaywall tab if oaDOI was able to find an open copy. This does cost an extra step, true. But it's only a few seconds difference, and has the substantial advantage the the behavior is very consistent and predictable for the user.

Thanks very much, however, for sharing this idea...and do not hesitate to keep sharing ideas as you think of them! We really appreciate your taking the time (and will work to deliver more timely responses in the future).

**Comment by jibe-b** [comment]
Ok @jasonpriem! I understand that it's out of Unpaywall's scope.

The job can be done well using https://github.com/einaregilsson/Redirector/issues

with the rule 

> doi.org -> OADOI.org
Redirect:

http*://doi.org/*
to:

https://oadoi.org/$2
Example:

https://doi.org/ → https://oadoi.org/
Applies to:

Main window (address bar), XMLHttpRequests (Ajax)


more links:
- http://einaregilsson.com/writing-a-browser-extension-for-three-browsers/
- https://addons.mozilla.org/en-US/firefox/addon/redirector/?src=search
