### ISSUE TITLE
False negative

### ISSUE THREAD

**Issue by JennaMalkin** [Impactstory/unpaywall#19]
http://journals.sagepub.com/doi/10.1177/1746847713519386 - displays as being unavailable, but is available via https://www.researchgate.net/profile/Xavier_Minguez_Lopez/publication/260923534_Folktales_and_Other_References_in_Toriyama%27s_Dragon_Ball/links/00b49532c22d2de163000000/Folktales-and-Other-References-in-Toriyamas-Dragon-Ball.pdf 

Please fix this and consider using researchgate.net as a source for finding free copies of journal articles.  Thank you.

**Comment by eocarragain** [comment]
A version is also available from a repository: http://hdl.handle.net/10550/44043

**Comment by TheRadialActive** [comment]
Same here: https://www.openaire.eu/search/publication?articleId=od______2659::a9bfc5d280d764dca01eaa1559ef33a9 But this time more visible: The link to zenodo is already on the page.

**Comment by hpiwowar** [comment]
Hi!  Looks like the API is now picking up the version @eocarragain mentioned, so will close this ticket.  

(We don't include researchgate because too many of its papers are posted illegally.  
I'm not quite sure what you are looking for in the zenodo situation @TheRadialActive.  Could you open a different ticket with what you are trying to do using Unpaywall / what DOI you are giving it, and what error you see?)

**Comment by JennaMalkin** [comment]
Thanks @hpiwowar !
