### ISSUE TITLE
Discrepancy between oaDOI and unpaywall?

### ISSUE THREAD

**Issue by ioverka** [Impactstory/unpaywall#21]
Dear Heather & Jason,

is there a data discrepancy between oaDOI and unpaywall?

Example:  10.1017/jns.2017.43

Bronze OA tab:
![cup-bronze-tab](https://user-images.githubusercontent.com/8920469/30432564-58f8342c-9962-11e7-9291-def3174ad5f8.png)

But the oaDOI API only reports it's closed: http://api.oadoi.org/10.1017/jns.2017.43
```
{
  "results": [
    {
      "algorithm_version": 1,
      "doi": "10.1017/jns.2017.43",
      "doi_resolver": null,
      "evidence": "closed",
      "free_fulltext_url": null,
      "is_boai_license": false,
      "is_free_to_read": false,
      "is_subscription_journal": true,
      "license": null,
      "oa_color": null,
      "reported_noncompliant_copies": [],
      "url": "http://doi.org/10.1017/jns.2017.43"
    }
  ]
}
```

... in the meantime, I'll contact CUP and request them to report license information to CrossRef ;)

Thanks for your marvelous work,
inga

**Comment by hpiwowar** [comment]
Yes, Unpaywall queries Google Scholar if oaDOI does not find any open
copies.  The Google Scholar check can be disabled in a user's Unpaywall
settings.  We may also remove the Google Scholar check in future versions
of Unpaywall as oaDOI keeps getting better :)

Sincerely,
Heather

--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by eocarragain** [comment]
@hpiwowar @jasonpriem Querying Google Scholar appears to have already been removed in the latest commits. This is very interesting. I would have thought this would have a significant negative impact on unpaywall, most notably because it will no longer find ResearchGate material. Could you say a little bit more about the rationale? Perhaps oaDOI is simply getting to be comprehensive enough? Thanks,
Eoghan

**Comment by jasonpriem** [comment]
Yep, you said it right. It does hurt our recall a bit, but not as much as it once would've, since oaDOI is becoming a lot more comprehensive. 

Based on our log analysis, oaDOI (which includes no RG or Academia) is delivering OA copies for 47% of papers that actual users view. You can read lots more detail about this in our recent paper here: https://peerj.com/preprints/3119v1/

So, the improvement in oaDOI made us feel pretty good about removing the GS calls. And we've been getting more feedback from folks that the inclusion of RG/Academia results was confusing or problematic for users (esp potential institutional users), and so we figure now's a good time to remove them. 

All that said, leaving this issue open because oaDOI is still reporting the example at the top of the thread wrong. This will probably resolve itself in the next month or two as everything moves to data_standard=2 (see the v2 API docs for more details).

**Comment by jibe-b** [comment]
worth reading https://twitter.com/Protohedgehog/status/909053304042336256 on RG news.

**Comment by eocarragain** [comment]
Thanks @jasonpriem. That is very interesting & great that oaDOI is reaching this point of maturity. The discussion and definition in the peerj preprint are very useful. The update from @jibe-b re RG is also very relevant. Thanks

**Comment by hsldiane** [comment]
Today I encountered just the reverse - this DOI was listed as open in the OADOI API, while the Unpaywall plugin correctly listed it as *not* open.  
10.1142/S0192415X08005916
When will it be removed from the OADOI database?  
Also: is there a place we should be reporting issues like this, when OADOI says an article is free but it isn't?  
Thanks for your help!

**Comment by ioverka** [comment]
I'm not able to reproduce the last reported issue, see https://api.oadoi.org/10.1142/S0192415X08005916 as well as https://api.unpaywall.org/10.1142/S0192415X08005916. Where have you found the problem?

Note: The name oaDOI has been retired recently (see https://twitter.com/unpaywall_data/status/957384991360667648) - so I believe that there shouldn't be a huge discrepancy any longer.

**Comment by eocarragain** [comment]
Also, the v2 API shows this as closed: https://api.unpaywall.org/v2/10.1142/S0192415X08005916

**Comment by richard-orr** [comment]
Closing since the underlying functionality has changed substantially and the examples are now being reported correctly.

Note that it's still possible to see a discrepancy between the plugin and API [as described here](https://support.unpaywall.org/support/solutions/articles/44001781069-why-does-the-unpaywall-plugin-say-this-paywalled-article-is-open-access-).
