### ISSUE TITLE
Bulletin of the American Museum of Natural History, greenOA copies not found

### ISSUE THREAD

**Issue by rossmounce** [Impactstory/unpaywall#30]
**The problem:** 
Unpaywall does not seem to find the greenOA copies of articles from this journal as accessed at the paywalled version at BioOne

**Some explanation:**
BioOne assigns DOIs and is in some sense(?) the digital publisher for _Bulletin of the American Museum of Natural History_ , however in parallel to this ALL articles from the Bulletin are also made available at an AMNH IR, immediate (no embargo) greenOA.

e.g. 
Voss, R. S. and Fleck, D. W. 2017. Mammalian diversity and matses ethnomammalogy in amazonian peru part 2: Xenarthra, carnivora, perissodactyla, artiodactyla, and sirenia. Bulletin of the American Museum of Natural History pp. 1-118 http://doi.org/10.1206/00030090-417.1.1 

is also available at: http://digitallibrary.amnh.org/handle/2246/6783

It seems to be true for every landing page at BioOne that I tried, that Unpaywall does not yet find the free version. If fixed it would add an extra 418 items (I think strictly they are monographs not articles), that are freely available with Unpaywall 😃

**Comment by rossmounce** [comment]
Likewise there is the exact same problem for 

_American Museum Novitates_  at BioOne
and the greenOA copies of all AMV articles available at http://digitallibrary.amnh.org/handle/2246/9

e.g. https://doi.org/10.1206/3887.1  == http://digitallibrary.amnh.org/handle/2246/6816 

If fixed/mapped this would add an extra 3893(?) articles that are freely available with Unpaywall. Worth fixing!!!

**Comment by hpiwowar** [comment]
Hi Ross, 

Thanks for the bug report!  We do currently harvest from the American Museum of Natural History Digital Repository .

The problem seems to be that the AMNH modifies the title of the articles they host, appending the journal title and volume to the article titles.  This means they no longer match the Crossref titles, and our DOI matching algorithms naturally fail. 

We haven't found other repositories that modify the article titles like this.  I wish this repo wouldn't!  It seems they are dirtying the data.

Anyway, we're on it and we'll figure out a way to remove this extra biblio from the end of the titles in these cases and get the matches going.  Will keep you posted.

Heather

**Comment by hpiwowar** [comment]
Made harder because sometimes the title is appended without parentheses :(
eg http://digitallibrary.amnh.org/handle/2246/1220

**Comment by hpiwowar** [comment]
Progress!  Matching in most cases now, based on some quick QA, and most links working.  Will do more through QA soon, and fix anything still broken.

green tab:  https://i.imgur.com/7H8hGKa.png
:)

**Comment by hpiwowar** [comment]
All looks good from here!  Closing.
