### ISSUE TITLE
Fallback option to university proxies?

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/unpaywall#34]
Could you provide a hook to allow a fall back to university proxies?

**Comment by jasonpriem** [comment]
This is on the "possible" roadmap. It's a lot of work to integrate all the various login and proxy methods that different universities use, and it strays a bit from the simplicity of the add-on as it now exists...instead of "we find OA papers" it's "we find OA papers, or toll-access ones if your institution has paid for them and you sign in."

That said, of course it would be pretty handy for folks who do have paid access. So we're continuing to gather feedback. Counting this as a +1 :)

**Comment by jameshowison** [comment]
Yeah, I wonder if it is worth it over the combination of Google Scholar Button which provides the "Find it at" link if you've set your institution up in Google Scholar. Perhaps it's just an API into which plugins written by others could fit.  But users would probably see the plugins as part of unpaywall.  Maybe it's a totally different extension that just exposes the underlying database, mapping from URL to json metadata about a publication that other services in many ways.

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/aecf723317ad490d1903a5f33c79f7d124ac7dd1e16f951c478d5117cc302f64
